app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


// 사용자 인증
Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout'] );



// 사용자 등록 처리
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');


//패스워드 초기화
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');


// Categories
Route::resource('categories', 'CategoryController', ['except' => ['create']]);


// Tags
Route::resource('tags', 'TagController', ['except' => ['create']]);

//
// 정규 표현식을 이용하여 URL을 사전 검증할 수 있다..
// slug 의 경우 숫자와 문자만 '-', '_' 만 허용되기 때문에 아래와 같이 정규표현식으로 검증한다.
//
Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');


Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
Route::get('contact', 'PageController@getContact');
Route::get('about', 'PageController@getAbout');
Route::get('/', 'PageController@getIndex');
Route::resource('posts', 'PostController');


Route::get('teacher', ['middleware' => ['auth', 'roles'], 'uses' => 'TestController@getTeacher', 'roles' => ['administrator', 'teacher']]);


Route::get('student', ['middleware' => ['auth', 'roles'], 'uses' => 'TestController@getStudent', 'roles' => ['administrator', 'teacher', 'student']]);

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts()
    {
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Tag;
use Session;

class TagController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();

        return view('tags.index')->with('tags', $tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255'
        ]);

        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        Session::flash('success', 'New tag was successfully created..');


        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $tag = Tag::find($id);
        return view('tags.show')->withTag($tag);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $tag = Tag::find($id);
        return view('tags.edit')->withTag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:255'
        ]);

        $tag = Tag::find($id);

        $tag->name = $request->name;

        $tag->save();

        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/tags/edit.blade.php
@extends('main')

@section('title', '| Edit Tag')


@section('content')

    <div class="row">

        <h1> Edit Tag </h1>

        {!! Form::model($tag, ['route' => ['tags.update', $tag->id], 'method' => 'PUT']) !!}

        {{ Form::label('name', 'Name: ') }}
        {{ Form::text('name', null, ['class' => 'form-control']) }}

        {{ Form::submit('Save changes', ['class' => 'btn btn-success']) }}
        {{ Form::close() }}
    </div>



@endsection

resources/views/tags/index.blade.php
@extends('main')

@section('title', '| All Tags')


@section('content')

    <div class="row">

        <div class="col-md-8">

            <h1> Tags </h1>
            <table class="table">
                <thead>

                    <tr>

                        <th> # </th>
                        <th> Name </th>
                    </tr>
                </thead>

                <tbody>

                    @foreach ($tags as $tag)
                        <tr>
                            <td> {{ $tag->id }} </td>
                            <td> <a href="{{route('tags.show', $tag->id)}}">{{ $tag->name }}</a> </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div class="col-md-3">

            <div class="well">

                {!! Form::open(['route' => 'tags.store', 'method' => 'POST']) !!}
                <h2> New Tag </h2>

                {{ Form::label('name', 'Name: ') }}
                {{ Form::text('name', null, ['class' => 'form-control']) }}

                {{ Form::submit('Create New Tag', ['class' => 'btn btn-primary btn-block form-top-spacing']) }}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/tags/show.blade.php
@extends('main')
@section('title', "| $tag->name Tag")


@section('content')


    <div class="row">

        <div class="col-md-8">
            <h1> {{$tag->name}} Tag <small> {{$tag->posts()->count()}} Posts </small </h1>
        </div>

        <div class="col-md-2 col-md-offset-2">
            <a href="{{route('tags.edit', $tag->id)}}" class="btn btn-primary pull-right btn-block">Edit</a>
        </div>
    </div>

    <div class="row">

        <div class="col-md-12">

            <table class="table">

                <thead>

                    <tr>
                        <th> # </th>
                        <th> Title </th>
                        <th> Tags </th>
                        <th> </th>
                    </tr>
                </thead>


                <tbody>

                    @foreach ($tag->posts as $post)
                        <tr>
                            <th> {{$post->id}} </th>
                            <td> {{$post->title}} </td>
                            <td>
                                @foreach ($post->tags as $tag)
                                    <span class="label label-default"> {{ $tag->name }}</span>
                                @endforeach
                            </td>
                            <td>
                                <a href="{{route('posts.show', $post->id)}}" class="btn btn-default btn-small">View </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>


@endsection