app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


// 사용자 인증
Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout'] );



// 사용자 등록 처리
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');


//패스워드 초기화
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');


// Categories
Route::resource('categories', 'CategoryController', ['except' => ['create']]);


// Tags
Route::resource('tags', 'TagController', ['except' => ['create']]);

//
// 정규 표현식을 이용하여 URL을 사전 검증할 수 있다..
// slug 의 경우 숫자와 문자만 '-', '_' 만 허용되기 때문에 아래와 같이 정규표현식으로 검증한다.
//
Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');


Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
Route::get('contact', 'PageController@getContact');
Route::get('about', 'PageController@getAbout');
Route::get('/', 'PageController@getIndex');
Route::resource('posts', 'PostController');


Route::get('teacher', ['middleware' => ['auth', 'roles'], 'uses' => 'TestController@getTeacher', 'roles' => ['administrator', 'teacher']]);


Route::get('student', ['middleware' => ['auth', 'roles'], 'uses' => 'TestController@getStudent', 'roles' => ['administrator', 'teacher', 'student']]);

resources/views/partials/_footer.blade.php
<hr />
<footer>
<p>&copy; 2016 venturebridge.co.kr </p>
</footer>

resources/views/partials/_head.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Coozplz Blog @yield('title')</title>


        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        @yield('stylesheets')
    </head>

resources/views/partials/_messages.blade.php
@if (Session::has('success'))
    <div class="alert alert-success" role="alert">
        <strong> Success:</strong> {{ Session::get('success') }}
    </div>
@endif


@if (count($errors) > 0)
    <div class="alert alert-danger" role="alert">

        <strong> Error:</strong>

        <ul>
        @foreach ($errors->all() as $error)

           <li> {{ $error }} </li>
        @endforeach
        </ul>
    </di>v

@endif

resources/views/partials/_nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Coozplz Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{{ Request::is('/') ? 'active' : ''}}"><a href="/">Home</a></li>
                <li class="{{ Request::is('blog') ? 'active' : ''}}"><a href="/blog"> Blog</a> </li>
                <li class="{{ Request::is('contact') ? 'active' : ''}}"><a href="/contact">Contact</a></li>
                <li class="{{ Request::is('about') ? 'active' : ''}}"><a href="/about">About</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if (Auth::check())
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {{ Auth::user()->email }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('posts.index') }}">Posts</a></li>
                        <li><a href="{{ route('categories.index') }}"> Categories</a></li>
                        <li><a href="{{ route('tags.index') }}">Tags</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
                @else


                @if (!Request::is('auth/login'))
                    <a href="{{ route('login') }}" class="btn btn-default"> Login </a>
                @endif
                @endif
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

resources/views/partials/_scripts.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

resources/views/partials/_stylesheets.blade.php
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">