app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


// 사용자 인증
Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout'] );



// 사용자 등록 처리
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');


//패스워드 초기화
Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\PasswordController@reset');


// Categories
Route::resource('categories', 'CategoryController', ['except' => ['create']]);


// Tags
Route::resource('tags', 'TagController', ['except' => ['create']]);

//
// 정규 표현식을 이용하여 URL을 사전 검증할 수 있다..
// slug 의 경우 숫자와 문자만 '-', '_' 만 허용되기 때문에 아래와 같이 정규표현식으로 검증한다.
//
Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');


Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
Route::get('contact', 'PageController@getContact');
Route::get('about', 'PageController@getAbout');
Route::get('/', 'PageController@getIndex');
Route::resource('posts', 'PostController');


Route::get('teacher', ['middleware' => ['auth', 'roles'], 'uses' => 'TestController@getTeacher', 'roles' => ['administrator', 'teacher']]);


Route::get('student', ['middleware' => ['auth', 'roles'], 'uses' => 'TestController@getStudent', 'roles' => ['administrator', 'teacher', 'student']]);

resources/views/pages/about.blade.php
@extends('main')

@section('title', '| About')
@section('stylesheet')

@endsection
@section('content')
    <div class="page-header">
        <h1> About us... </h1>
    </div>
@endsection


@section('scripts')

@endsection

resources/views/pages/contact.blade.php
@extends('main')

@section('title', '| Contact')
@section('stylesheets')
@endsection
@section('content')
<div class="page-header">
    <h1> Contact me</h1>
    <p> Please fill in the blank... </p>
</div>


<form class="form-horizontal" role="form">

    <div class="form-group">
        <label for="name">Name :</label>
        <input type="name" class="form-control" id="name">
    </div>
    <div class="form-group">
        <label for="email">Email address :</label>
        <input type="email" class="form-control" id="email">
    </div>

    <div class="form-group">
        <label for="phone">Mobile :</label>
        <input type="phone" class="form-control" id="phone">
    </div>

    <div class="form-group">
        <label for="message"> Message : </label>
        <textarea class="form-control" row="5" id="message"> </textarea>
    </div>

    <div class="btn-group pull-right">
        <div class="btn-group">
            <button type="button" class="btn btn-primary">Submit</button>
        </div>
        <div class="btn-group">
            <button type="button" class="btn btn-default">Cancel</button>
        </div>
    </div>
</form>
@endsection

@section('scripts')
@endsection

resources/views/pages/create.blade.php
@extends('main')

@section('title', '| Create')


@section('stylesheets')
    {!! Html::style('css/parsley.css') !!}
    {!! Html::style('css/select2.min.css') !!}
@endsection

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1> Create Post</h1>
            <hr>


            {!! Form::open(array('route' => 'posts.store', 'data-parsley-validate' => '')) !!}
                {{ Form::label('title', 'Title:') }}
                {{ Form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

                {{ Form::label('slug', 'Slug: ') }}
                {{ Form::text('slug', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255', 'minlength' => '5')) }}

                {{ Form::label('category_id', 'Category: ') }}
            <select class="form-control" name="category_id">
                @foreach ($categories as $category)
                    <option value="{{ $category->id }}"> {{ $category->name }} </option>
                @endforeach
            </select>

                {{ Form::label('tags', 'Tags: ') }}
            <select class="form-control select2-multi" name="tags[]" multiple="multiple">
                @foreach ($tags as $tag)
                    <option value="{{ $tag->id }}"> {{$tag->name}} </option>
                @endforeach
            </select>

                {{ Form::label('body', "Post Body:") }}
                {{ Form::textarea('body', null, array('class' => 'form-control', 'required' => ''))}}

                {{ Form::submit('Create Post', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;')) }}

            {!! Form::close() !!}
        </div>
    </div>

@endsection

@section('scripts')
    {!! Html::script('/js/parsley.min.js') !!}
    {!! Html::script('/js/select2.min.js') !!}
    <script type="text/javascript">
     $('.select2-multi').select2();
    </script>
@endsection

resources/views/pages/edit.blade.php
@extends('main')

@section('title', '| Edit Blog Post')

@section('stylesheets')
    {!! Html::style('css/parsley.css') !!}
    {!! Html::style('css/select2.min.css') !!}
@endsection


@section('content')

    <div class="row">

         {!! Form::model($post, ['route' => ['posts.update', $post->id], 'method' => 'put']) !!}
        <div class="col-md-8">
            {{ Form::label('title', 'Title:') }}
            {{ Form::text('title', null, ['class' => 'form-control input-lg' ]) }}


            {{ Form::label('slug', 'Slug: ') }}
            {{ Form::text('slug', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255', 'minlength' => '5')) }}


            {{ Form::label('category_id', 'Category: ') }}
            {{ Form::select('category_id', $categories, null, ['class' => 'form-control']) }}

            {{ Form::label('tags', 'Tags: ', ['class' => 'form-spacing-top']) }}
            {{ Form::select('tags[]', $tags, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) }}

            {{ Form::label('body', 'Body: ') }}
            {{ Form::textarea('body', null, ['class' => 'form-control']) }}

        </div>


        <div class="col-md-4">
            <div class="well">

                <dl class="dl-horizontal">
                    <dt>Create At: </dt>
                    <dd>{{ date('M j, Y h:ia', strtotime($post->created_at)) }} </dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt> Last updated: </dt>
                    <dd>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</dd>
                </dl>
                <hr/>


                <div class="row">
                    <div class="col-sm-6">
                        {!! Html::linkRoute('posts.show', 'Cancel', array($post->id), array('class' => 'btn btn-danger btn-block')) !!}
                    </div>

                    <div class="col-sm-6">
                        {{ Form::submit('Save changes', ['class' => 'btn btn-success btn-block']) }}
                    </div>

                </div>

            </div>


        </div>
        {!! Form::close() !!}


    </div>



@endsection

@section('scripts')
    {!! Html::script('js/select2.min.js') !!}

    <script type="text/javascript">
     $('.select2-multi').select2();
     $('.select2-multi').select2().val({!! json_encode($post->tags()->getRelatedIds()) !!}).trigger('change');
    </script>
@endsection

resources/views/pages/index.blade.php
@extends('main')


@section('title', '| All Posts')


@section('content')

    <div class="row">
        <div class="col-md-10">
            <h1> All Posts</h1>
        </div>

        <div class="col-md-2">
            <a href="{{ route('posts.create')}}" class="btn btn-lg btn-block btn-primary"> Create Post </a>
        </div>
        <div class="col-md-12">
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <th> # </th>
                    <th> Category </th>
                    <th> Title </th>
                    <th> Body </th>
                    <th> Created At </th>
                    <th>  </th>
                </thead>

                <tbody>
                    @foreach ($posts as $post)
                        <tr>

                            <td>{{ $post->id }} </td>
                            <td> {{ $post->category->name }}
                            <td>{{ substr($post->title, 0, 50) }} {{ strlen($post->title) > 50 ? "..." : "" }} </td>
                            <td>{{ substr($post->body, 0, 250) }} {{ strlen($post->body) > 250 ? "..." : "" }} </td>
                            <td>{{ date('M j, Y', strtotime($post->created_at)) }} </td>
                            <td><a href="/posts/{{ $post->id  }}" class="btn btn-default"> View </a> <a href="/posts/{{ $post->id }}/edit" class="btn btn-default"> Edit </a> </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>

            <div class="text-center">
                {!! $posts->links(); !!}
            </div>

        </div>

    </div>

@endsection

resources/views/pages/show.blade.php
@extends('main')

@section('title', '| View Post')

@section('content')
    <div class="row">
        <div class="col-md-8">

            <h1> {{ $post->title }} </h1>
            <p class="lead"> {{ $post->body }} </p>
            <hr>

            <div class="tags">
                @foreach ($post->tags as $tag)
                    <span class="label label-default">{{ $tag->name }}</span>
                @endforeach

            </div>
        </div>


        <div class="col-md-4">
            <div class="well">

                <dl class="dl-horizontal">
                    <label>Url slug: </label>
                    <p><a href="{{ url('/blog/' . $post->slug)}}"> {{ url('/blog/' . $post->slug) }}</a> </p>
                </dl>

                <dl class="dl-horizontal">
                    <label>Category:  </label>
                    <p>{{ $post->category->name }} </p>
                </dl>

                <dl class="dl-horizontal">
                    <label>Create At: </label>
                    <p>{{ date('M j, Y h:ia', strtotime($post->created_at)) }} </p>
                </dl>
                <dl class="dl-horizontal">
                    <label> Last updated: </label>
                    <p>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</p>
                </dl>
                <hr/>


                <div class="row">
                    <div class="col-sm-6">
                        {!! Html::linkRoute('posts.edit', 'Edit', array($post->id), array('class' => 'btn btn-primary btn-block')) !!}
                    </div>

                    <div class="col-sm-6">
                        {!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) !!}
                        {!! Form::close() !!}
                    </div>


                </div>

                <div class="row">
                    <a href="/posts/" class="btn btn-block btn-default"> See all posts </a>
                </div>

            </div>


        </div>


    </div>


@endsection

resources/views/pages/student.blade.php
@extends('main')

@section('title', '| Student')
@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1> Student's page</h1>
                <p class="lead"> Thank you so much for visiting...</p>
                <p><a class="btn btn-primary btn-lg" href="#" role="button">Popular post </a></p>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/teacher.blade.php
@extends('main')

@section('title', '| Teacher')
@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1> Teacher's page</h1>
                <p class="lead"> Thank you so much for visiting...</p>
                <p><a class="btn btn-primary btn-lg" href="#" role="button">Popular post </a></p>
            </div>
        </div>
    </div>
@endsection